spring:
  application:
    name: habits
  datasource:
    url: jdbc:postgresql://localhost:5433/y_lab
    username: y_lab_user
    password: Y_lab_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
log-package-starter:
  env: y_lab.service